name: cd

on:
    push:
        branches:
            - BranchIntegration

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.8.1
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test

            - name: Build
              run: npm run build

            - name: Run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                  npx semantic-release
